# Generated by Django 4.2.2 on 2024-08-25 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите создателя раздела",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="examination",
            field=models.ForeignKey(
                help_text="Введите к какому тестированию знаний относится вопрос",
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.examination",
                verbose_name="Тестирование знаний",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                help_text="Введите к какому разделу относится урок",
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.section",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите создателя урока",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="lesson",
            field=models.ForeignKey(
                help_text="Введите к какому уроку относится тестирование знаний",
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите создателя теста",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="materials.question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="materials.choice"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="materials.question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
