# Generated by Django 4.2.2 on 2024-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
